development:
  adapter: postgresql
  encoding: unicode
  database: rcop_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: rcop_test
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: rcop_production
  pool: 1

